import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Common
    Search: 'Search',
    SearchCompanies: 'Search by name, code or contact',
    SearchProducts: 'Search by name or code',
    SearchRetailers: 'Search by name, phone or area',
    SearchSales: 'Search by invoice no or retailer',
    SearchPayments: 'Search by payment no, retailer or ref',
    SearchStock: 'Search by product name or code',
    SearchUsers: 'Search by username, name, email or phone',
    Loading: 'Loading...',
    Save: 'Save',
    Cancel: 'Cancel',
    Delete: 'Delete',
    Edit: 'Edit',
    Add: 'Add',
    Actions: 'Actions',
    View: 'View',
    Print: 'Print',
    Status: 'Status',
    Active: 'Active',
    Inactive: 'Inactive',
    Yes: 'Yes',
    No: 'No',
    Name: 'Name',
    Code: 'Code',
    Phone: 'Phone',
    Address: 'Address',
    Email: 'Email',
    Date: 'Date',
    Time: 'Time',
    Total: 'Total',
    Amount: 'Amount',
    Quantity: 'Quantity',
    Price: 'Price',
    Type: 'Type',
    Note: 'Note',
    Notes: 'Notes',
    Error: 'Error',
    Success: 'Success',
    Warning: 'Warning',
    Info: 'Info',
    Required: 'Required',
    Optional: 'Optional',
    NoDataFound: 'No Data Found',
    ConfirmDelete: 'Are you sure you want to delete?',
    DeleteSuccess: 'Deleted successfully',
    SaveSuccess: 'Saved successfully',
    UpdateSuccess: 'Updated successfully',
    DeleteError: 'Failed to delete',
    SaveError: 'Failed to save',

    // Navigation
    Dashboard: 'Dashboard',
    Orders: 'Orders',
    Companies: 'Companies',
    Products: 'Products',
    Retailers: 'Retailers',
    Sales: 'Sales',
    Payments: 'Payments',
    RetailerRequired: 'Please select a retailer',
    AmountRequired: 'Please enter amount',
    StockNav: 'Stock',
    Reports: 'Reports',
    Users: 'Users',
    Settings: 'Settings',
    MyProfile: 'My Profile',
    Menu: 'Menu',
    LoggedInAs: 'Logged in as',
    Logout: 'Logout',
    ChangePassword: 'Change Password',
    English: 'English',
    Bangla: 'Bangla',
    Language: 'Language',
    DefaultLanguage: 'Default Language',
    SystemInformation: 'System Information',
    Notifications: 'Notifications',
    MarkAllAsRead: 'Mark All as Read',
    SearchNotifications: 'Search notifications...',
    NoNotifications: 'No notifications',
    PublicMessages: 'Public Messages',
    LowStock: 'Low Stock',
    ProductExpiry: 'Product Expiry',
    Invoice: 'Invoice',
    InvoiceDue: 'Invoice Due',
    PaymentReceived: 'Payment Received',
    FieldDisabled: 'Field Disabled',
    AllNotifications: 'All Notifications',
    MarkAsRead: 'Mark as Read',
    Title: 'Title',
    Message: 'Message',
    ConfirmMarkAllRead: 'Mark All as Read?',
    ConfirmMarkAllReadMsg: 'Are you sure you want to mark all notifications as read?',
    ConfirmDeleteNotification: 'Are you sure you want to delete this notification? This action cannot be undone.',
    Confirm: 'Confirm',
    ViewDetails: 'View Details',
    Category: 'Category',
    Created: 'Created',
    Updated: 'Updated',
    Status: 'Status',
    Read: 'Read',
    Unread: 'Unread',
    Reference: 'Reference',
    ActionURL: 'Action URL',
    Close: 'Close',
    EntriesPerPage: 'Entries per page',
    Of: 'of',
    Previous: 'Previous',
    Next: 'Next',
    LowStockAlerts: 'Low Stock Alerts',
    ExpiryAlerts: 'Expiry Alerts',
    PaymentReminders: 'Payment Reminders',

    // Public Chat
    MessageWithDealer: 'Message with Dealer',
    NewChat: 'New Chat',
    TrackingCode: 'Tracking Code',
    YourName: 'Your Name',
    MobileNumber: 'Mobile Number',
    StartChat: 'Start Chat',
    EnterTrackingCode: 'Enter your 8-digit tracking code',
    ContinueChat: 'Continue Chat',
    TypeYourMessage: 'Type your message...',
    SendFirstMessage: 'Send your first message. The dealer will reply soon.',
    ChatSubtitle: 'Send a message to the dealer or enter your tracking code',
    AskAboutProducts: 'Ask about products',
    MessageDealer: 'Message the dealer',
    QuickAskHint: 'Know about product prices & stock',
    QuickMsgHint: 'Send a message to the dealer',
    Back: 'Back',
    DealerIsTyping: 'Dealer is typing...',
    Dealer: 'Dealer',
    SessionNotFound: 'Session not found. Please start a new chat.',
    Checking: 'Checking...',
    Starting: 'Starting...',
    Send: 'Send',
    EnterYourName: 'Enter your name',
    EnterYourPhone: 'Enter your mobile number',

    // Dashboard
    WelcomeToDMS: 'DMS Dashboard',
    TodaySales: "Today's Sales",
    TotalSales: 'Total Sales',
    TotalSalesAllTime: 'Total Sales (All Time)',
    TotalOutstanding: 'Total Outstanding',
    TotalProducts: 'Total Products',
    RecentSales: 'Recent Sales',
    LowStockProducts: 'Low Stock Products',
    NoSalesToday: 'No sales today',
    AllProductsWellStocked: 'All products are well stocked',
    CollectedAmount: 'Collected',
    DueLabel: 'Due',
    DailySalesReport: 'Daily Sales Report',
    ProductWiseSalesReport: 'Product-wise Sales Report',
    CompanyWiseSalesReport: 'Company-wise Sales Report',
    ProfitReport: 'Profit Report',
    StockReport: 'Stock Report',
    DueReport: 'Due Report',
    StartDate: 'Start Date',
    EndDate: 'End Date',
    InvoiceCount: 'Invoice Count',
    ProfitAmount: 'Profit',
    CategoryLabel: 'Category',
    Product: 'Product',
    Discount: 'Discount',
    CreatedBy: 'Created By',
    PurchaseOrders: 'Purchase Orders',
    NewPurchaseOrder: 'New Purchase Order',
    OrderNo: 'Order No',
    OrderDate: 'Order Date',
    OrderDetails: 'Order Details',
    ItemsCount: 'Items',
    Invoices: 'Invoices',
    TotalInvoices: 'Total Invoices',
    Collected: 'Collected',
    TotalQuantity: 'Total Quantity',
    TotalCompanies: 'Total Companies',
    TotalCost: 'Total Cost',
    TotalProfit: 'Total Profit',
    TotalRetailers: 'Total Retailers',
    Expired: 'Expired',
    ExpiringSoon: 'Expiring Soon',
    TotalDue: 'Total Due',

    // Products
    AddProduct: 'Add Product',
    EditProduct: 'Edit Product',
    ProductName: 'Product Name',
    Category: 'Category',
    Company: 'Company',
    PurchasePrice: 'Purchase Price',
    DealerPrice: 'Dealer Price',
    MRP: 'MRP',
    StockLabel: 'Stock',
    Unit: 'Unit',
    PackSize: 'Pack Size',
    LowStockAlert: 'Low Stock Alert',
    ExpiryDate: 'Expiry Date',
    ExpiredProducts: 'Expired Products',
    ExpiryProducts: 'Expiry Products',
    StockValue: 'Stock Value',
    NoProductsFound: 'No products found',
    InsufficientStock: 'Insufficient stock',

    // Users
    AddUser: 'Add User',
    EditUser: 'Edit User',
    Username: 'Username',
    FullName: 'Full Name',
    Role: 'Role',
    Password: 'Password',
    ConfirmPassword: 'Confirm Password',
    SystemAdmin: 'System Admin',
    Admin: 'Admin',
    Manager: 'Manager',
    Salesman: 'Salesman',
    Accountant: 'Accountant',
    Driver: 'Driver',
    Loader: 'Loader',
    NoUsersFound: 'No users found',

    // Settings
    GeneralSettings: 'General Settings',
    General: 'General',
    Roles: 'Roles',
    Profile: 'Profile',
    CompanyInfo: 'Company Info',
    InvoiceSettings: 'Invoice Settings',
    LowStockThreshold: 'Low Stock Threshold',

    // Role Management
    AddRole: 'Add Role',
    EditRole: 'Edit Role',
    DeleteRole: 'Delete Role',
    RoleName: 'Role Name',
    
    // Role Names
    system_admin: 'System Admin',
    admin: 'Admin',
    manager: 'Manager',
    salesman: 'Salesman',
    accountant: 'Accountant',
    driver: 'Driver',
    loader: 'Loader',
    
    // Permission IDs
    all: 'All Access',
    products: 'Products',
    retailers: 'Retailers',
    sales: 'Sales',
    payments: 'Payments',
    stock: 'Stock',
    reports: 'Reports',
    companies: 'Companies',
    users: 'Users',
    view_deliveries: 'View Deliveries',
    Description: 'Description',
    Permissions: 'Permissions',
    Color: 'Color',
    AllAccess: 'All Access',
    ManageProducts: 'Manage Products',
    ManageRetailers: 'Manage Retailers',
    CreateSales: 'Create Sales',
    ManagePayments: 'Manage Payments',
    ManageStock: 'Manage Stock',
    ViewReports: 'View Reports',
    ManageCompanies: 'Manage Companies',
    ManageUsers: 'Manage Users',
    ViewDeliveries: 'View Deliveries',
    RoleManagement: 'Role Management',
    RoleAdded: 'Role added successfully',
    RoleUpdated: 'Role updated successfully',
    RoleDeleted: 'Role deleted successfully',
    CannotDeleteSystemRole: 'Cannot delete system role',
    CannotDeleteRoleWithUsers: 'Cannot delete role - users are assigned to this role',
    RoleNameRequired: 'Role name is required',
    PermissionsRequired: 'At least one permission is required',

    // Auth
    Login: 'Login',
    ForgotPassword: 'Forgot Password?',
    ResetPassword: 'Reset Password',
    CurrentPassword: 'Current Password',
    NewPassword: 'New Password',
    LoginFailed: 'Login failed',
    InvalidCredentials: 'Invalid credentials',
    PasswordChanged: 'Password changed successfully',
    PasswordMismatch: 'Passwords do not match',
    PasswordTooShort: 'Password must be at least 6 characters',
    SendResetLink: 'Send Reset Link',
    BackToLogin: 'Back to Login',
    PasswordResetLinkSent: 'Password reset link has been sent to your email',
    EnterAmount: 'Enter',
    TryAgain: 'Please try again',
    Redirecting: 'Redirecting',
    Access: 'Control',
    Cheque: 'Cheque',
    Or: 'or',
    Default: 'Default',
    AccountDeactivated: 'Your account has been deactivated. Please contact administrator.',
    Page: 'Page',
    RecordPayment: 'Record Payment',
    PaymentNo: 'Payment No',
    PaymentMethod: 'Payment Method',
    ReferenceNo: 'Reference No',
    PaymentDate: 'Payment Date',
    CollectedBy: 'Collected By',
    NoPaymentsFound: 'No Payments Found',
    SelectRetailerPayment: 'Select Retailer',
    EnterAmountPayment: 'Enter Amount',
  },
  bn: {
    // Common
    Search: 'অনুসন্ধান',
    SearchCompanies: 'নাম, কোড বা যোগাযোগ দ্বারা খুঁজুন',
    SearchProducts: 'নাম বা কোড দ্বারা খুঁজুন',
    SearchRetailers: 'নাম, ফোন বা এলাকা দ্বারা খুঁজুন',
    SearchSales: 'ইনভয়েস নম্বর বা রিটেইলার দ্বারা খুঁজুন',
    SearchPayments: 'পেমেন্ট নম্বর, রিটেইলার বা রেফ দ্বারা খুঁজুন',
    SearchStock: 'প্রোডাক্ট নাম বা কোড দ্বারা খুঁজুন',
    SearchUsers: 'ইউজারনেম, নাম, ইমেইল বা ফোন দ্বারা খুঁজুন',
    Loading: 'লোড হচ্ছে...',
    Save: 'সংরক্ষণ',
    Cancel: 'বাতিল',
    Delete: 'মুছুন',
    Edit: 'সম্পাদনা',
    Add: 'যোগ করুন',
    Actions: 'পদক্ষেপ',
    View: 'দেখুন',
    Print: 'প্রিন্ট',
    Status: 'স্ট্যাটাস',
    Active: 'সক্রিয়',
    Inactive: 'নিষ্ক্রিয়',
    Yes: 'হ্যাঁ',
    No: 'না',
    Name: 'নাম',
    Code: 'কোড',
    Phone: 'ফোন',
    Address: 'ঠিকানা',
    Email: 'ইমেইল',
    Date: 'তারিখ',
    Time: 'সময়',
    Total: 'মোট',
    Amount: 'টাকা',
    Quantity: 'পরিমাণ',
    Price: 'দাম',
    Type: 'ধরন',
    Note: 'নোট',
    Notes: 'নোট',
    Error: 'ত্রুটি',
    Success: 'সফল',
    Warning: 'সতর্কতা',
    Info: 'তথ্য',
    Required: 'আবশ্যক',
    Optional: 'ঐচ্ছিক',
    NoDataFound: 'কোনো তথ্য পাওয়া যায়নি',
    ConfirmDelete: 'আপনি কি মুছতে চান?',
    DeleteSuccess: 'সফলভাবে মুছে ফেলা হয়েছে',
    SaveSuccess: 'সফলভাবে সংরক্ষণ করা হয়েছে',
    UpdateSuccess: 'সফলভাবে আপডেট করা হয়েছে',
    DeleteError: 'মুছতে ব্যর্থ',
    SaveError: 'সংরক্ষণ করতে ব্যর্থ',

    // Navigation
    Dashboard: 'ড্যাশবোর্ড',
    Orders: 'অর্ডার',
    Companies: 'কোম্পানি',
    Products: 'প্রোডাক্ট',
    Retailers: 'রিটেইলার',
    Sales: 'বিক্রয়',
    Payments: 'পেমেন্ট',
    RetailerRequired: 'রিটেইলার নির্বাচন করুন',
    AmountRequired: 'টাকার পরিমাণ লিখুন',
    PublicMessages: 'পাবলিক মেসেজ',
    StockNav: 'স্টক',
    Reports: 'রিপোর্ট',
    Users: 'ইউজার',
    Settings: 'সেটিংস',
    MyProfile: 'আমার প্রোফাইল',
    Menu: 'মেনু',
    LoggedInAs: 'লগইন আছেন',
    Logout: 'লগআউট',
    ChangePassword: 'পাসওয়ার্ড পরিবর্তন',
    English: 'English',
    Bangla: 'বাংলা',
    Language: 'ভাষা',
    DefaultLanguage: 'ডিফল্ট ভাষা',
    SystemInformation: 'সিস্টেম তথ্য',
    Notifications: 'নোটিফিকেশন',
    MarkAllAsRead: 'সব পড়া হয়েছে',
    SearchNotifications: 'নোটিফিকেশন খুঁজুন...',
    NoNotifications: 'কোনো নোটিফিকেশন নেই',
    LowStock: 'কম স্টক',
    ProductExpiry: 'প্রোডাক্ট মেয়াদ',
    InvoiceDue: 'চালান বাকি',
    PaymentReceived: 'পেমেন্ট প্রাপ্ত',
    FieldDisabled: 'ফিল্ড নিষ্ক্রিয়',
    AllNotifications: 'সব নোটিফিকেশন',
    MarkAsRead: 'পড়া হয়েছে চিহ্নিত করুন',
    Title: 'শিরোনাম',
    Message: 'বার্তা',
    ConfirmMarkAllRead: 'সব পড়া হয়েছে চিহ্নিত করবেন?',
    ConfirmMarkAllReadMsg: 'আপনি কি নিশ্চিত যে সব নোটিফিকেশন পড়া হয়েছে চিহ্নিত করতে চান?',
    ConfirmDeleteNotification: 'আপনি কি নিশ্চিত যে এই নোটিফিকেশন মুছে ফেলতে চান? এই কাজ পূর্বাবস্থায় ফেরানো যাবে না।',
    Confirm: 'নিশ্চিত করুন',
    ViewDetails: 'বিস্তারিত দেখুন',
    Category: 'ক্যাটাগরি',
    Created: 'তৈরি হয়েছে',
    Updated: 'আপডেট হয়েছে',
    Status: 'অবস্থা',
    Read: 'পড়া হয়েছে',
    Unread: 'অপঠিত',
    Reference: 'রেফারেন্স',
    ActionURL: 'অ্যাকশন URL',
    Close: 'বন্ধ করুন',
    EntriesPerPage: 'প্রতি পৃষ্ঠায় এন্ট্রি',
    Of: 'এর',
    Previous: 'পূর্ববর্তী',
    Next: 'পরবর্তী',
    LowStockAlerts: 'কম স্টক অ্যালার্ট',
    ExpiryAlerts: 'মেয়াদ শেষ অ্যালার্ট',
    PaymentReminders: 'পেমেন্ট রিমাইন্ডার',

    // Dashboard
    WelcomeToDMS: 'ডিএমএস ড্যাশবোর্ড',
    TodaySales: 'আজকের বিক্রয়',
    TotalSales: 'মোট বিক্রয়',
    TotalSalesAllTime: 'সর্বমোট বিক্রয় (আজ পর্যন্ত)',
    TotalOutstanding: 'মোট বকেয়া',
    TotalProducts: 'মোট প্রোডাক্ট',
    RecentSales: 'সাম্প্রতিক বিক্রয়',
    LowStockProducts: 'কম স্টক প্রোডাক্ট',
    NoSalesToday: 'আজ কোনো বিক্রয় নেই',
    AllProductsWellStocked: 'সব প্রোডাক্ট যথেষ্ট স্টকে আছে',
    CollectedAmount: 'সংগ্রহিত',
    DueLabel: 'বাকি',
    Invoice: 'ইনভয়েস',
    Retailer: 'রিটেইলার',
    Product: 'প্রোডাক্ট',
    CreatedBy: 'তৈরি করেছেন',

    // Companies
    AddCompany: 'কোম্পানি যোগ করুন',
    EditCompany: 'কোম্পানি সম্পাদনা',
    CompanyName: 'কোম্পানির নাম',
    ContactPerson: 'যোগাযোগ ব্যক্তি',
    DueLimit: 'বাকি সীমা',
    BasicInformation: 'মৌলিক তথ্য',
    ContactInformation: 'যোগাযোগ তথ্য',
    CreditSettings: 'ক্রেডিট সেটিংস',

    // Products
    AddProduct: 'প্রোডাক্ট যোগ করুন',
    EditProduct: 'প্রোডাক্ট সম্পাদনা',
    ProductName: 'প্রোডাক্টের নাম',
    Category: 'ক্যাটাগরি',
    Company: 'কোম্পানি',
    PurchasePrice: 'ক্রয় মূল্য',
    DealerPrice: 'ডিলার দাম',
    MRP: 'এমআরপি',
    StockLabel: 'স্টক',
    Unit: 'ইউনিট',
    PackSize: 'প্যাক সাইজ',
    LowStockAlert: 'কম স্টক সতর্কতা',
    ExpiryDate: 'মেয়াদ তারিখ',
    ExpiredProducts: 'মেয়াদ উত্তীর্ণ পণ্য',
    ExpiryProducts: 'মেয়াদ উত্তীর্ণ পণ্য',
    StockValue: 'স্টক মূল্য',
    NoProductsFound: 'কোনো প্রোডাক্ট পাওয়া যায়নি',
    InsufficientStock: 'পর্যাপ্ত স্টক নেই',

    // Retailers
    AddRetailer: 'রিটেইলার যোগ করুন',
    EditRetailer: 'রিটেইলার সম্পাদনা',
    ShopName: 'দোকানের নাম',
    OwnerName: 'মালিকের নাম',
    Area: 'এলাকা',
    CreditLimit: 'ক্রেডিট লিমিট',
    Outstanding: 'বকেয়া',
    NoRetailersFound: 'কোনো রিটেইলার পাওয়া যায়নি',

    // Sales
    NewInvoice: 'নতুন ইনভয়েস',
    CreateInvoice: 'ইনভয়েস তৈরি',
    InvoiceNo: 'ইনভয়েস নম্বর',
    SelectRetailer: 'রিটেইলার নির্বাচন',
    SelectProduct: 'প্রোডাক্ট নির্বাচন',
    AddItem: 'আইটেম যোগ',
    Discount: 'ডিসকাউন্ট',
    DiscountPercent: 'ডিসকাউন্ট %',
    PaidAmount: 'পেইড অ্যামাউন্ট',
    Subtotal: 'সাবটোটাল',
    DueAmount: 'বাকি অ্যামাউন্ট',
    Paid: 'পেইড',
    Partial: 'আংশিক',
    NoInvoicesFound: 'কোনো ইনভয়েস পাওয়া যায়নি',
    SelectRetailerAndAddItems: 'রিটেইলার নির্বাচন করুন এবং আইটেম যোগ করুন',
    CreditLimitExceeded: 'ক্রেডিট লিমিট অতিক্রম',

    // Payments
    NewPayment: 'নতুন পেমেন্ট',
    RecordPayment: 'পেমেন্ট রেকর্ড',
    PaymentNo: 'পেমেন্ট নম্বর',
    PaymentMethod: 'পেমেন্ট মেথড',
    ReferenceNo: 'রেফারেন্স নম্বর',
    PaymentDate: 'পেমেন্ট তারিখ',
    CollectedBy: 'সংগ্রহ করেছেন',
    Cash: 'ক্যাশ',
    Bank: 'ব্যাংক',
    MobileBanking: 'মোবাইল ব্যাংকিং',
    NoPaymentsFound: 'কোনো পেমেন্ট পাওয়া যায়নি',
    SelectRetailerPayment: 'রিটেইলার নির্বাচন',
    EnterAmountPayment: 'টাকার পরিমাণ লিখুন',

    // Stock
    StockHistory: 'স্টক ইতিহাস',
    PurchaseOrders: 'পারচেস অর্ডার',
    NewPurchaseOrder: 'নতুন পারচেস অর্ডার',
    OrderNo: 'অর্ডার নম্বর',
    OrderDate: 'অর্ডার তারিখ',
    Received: 'গৃহীত',
    Pending: 'বিচারাধীন',
    In: 'ইন',
    Out: 'আউট',
    Adjustment: 'সমন্বয়',
    Reference: 'রেফারেন্স',
    NoStockHistory: 'কোনো স্টক ইতিহাস নেই',
    SelectCompany: 'কোম্পানি নির্বাচন',
    OrderDetails: 'অর্ডার বিবরণ',
    ItemsCount: 'আইটেম',
    ReceivedQuantity: 'গৃহীত পরিমাণ',

    // Reports
    DailySales: 'দৈনিক বিক্রয়',
    ProductWise: 'প্রোডাক্ট ওয়াইজ',
    CompanyWise: 'কোম্পানি ওয়াইজ',
    Profit: 'লাভ',
    DailySalesReport: 'দৈনিক বিক্রয় রিপোর্ট',
    ProductWiseSalesReport: 'প্রোডাক্ট ওয়াইজ বিক্রয় রিপোর্ট',
    CompanyWiseSalesReport: 'কোম্পানি ওয়াইজ বিক্রয় রিপোর্ট',
    ProfitReport: 'লাভ রিপোর্ট',
    StockReport: 'স্টক রিপোর্ট',
    DueReport: 'বকেয়া রিপোর্ট',
    StartDate: 'শুরুর তারিখ',
    EndDate: 'শেষ তারিখ',
    InvoiceCount: 'ইনভয়েস সংখ্যা',
    ProfitAmount: 'লাভ',
    CategoryLabel: 'ক্যাটাগরি',
    Invoices: 'ইনভয়েস',
    TotalInvoices: 'মোট ইনভয়েস',
    Collected: 'সংগ্রহিত',
    TotalQuantity: 'মোট পরিমাণ',
    TotalCompanies: 'মোট কোম্পানি',
    TotalCost: 'মোট খরচ',
    TotalProfit: 'মোট লাভ',
    TotalRetailers: 'মোট রিটেইলার',
    Expired: 'মেয়াদ উত্তীর্ণ',
    ExpiringSoon: 'শীঘ্রই মেয়াদ শেষ',
    TotalDue: 'মোট বকেয়া',

    // Users
    AddUser: 'ইউজার যোগ করুন',
    EditUser: 'ইউজার সম্পাদনা',
    Username: 'ইউজারনেম',
    FullName: 'পূর্ণ নাম',
    Role: 'রোল',
    Password: 'পাসওয়ার্ড',
    ConfirmPassword: 'পাসওয়ার্ড নিশ্চিত',
    SystemAdmin: 'সিস্টেম অ্যাডমিন',
    Admin: 'অ্যাডমিন',
    Manager: 'ম্যানেজার',
    Salesman: 'সেলসম্যান',
    Accountant: 'অ্যাকাউন্ট্যান্ট',
    Driver: 'ড্রাইভার',
    Loader: 'লোডার',
    NoUsersFound: 'কোনো ইউজার পাওয়া যায়নি',

    // Settings
    GeneralSettings: 'সাধারণ সেটিংস',
    General: 'সাধারণ',
    Roles: 'রোল',
    Profile: 'প্রোফাইল',
    CompanyInfo: 'কোম্পানি তথ্য',
    InvoiceSettings: 'ইনভয়েস সেটিংস',
    LowStockThreshold: 'কম স্টক থ্রেশহোল্ড',

    // Role Management
    AddRole: 'রোল যোগ করুন',
    EditRole: 'রোল সম্পাদনা',
    DeleteRole: 'রোল মুছুন',
    RoleName: 'রোল নাম',
    
    // Role Names
    system_admin: 'সিস্টেম অ্যাডমিন',
    admin: 'অ্যাডমিন',
    manager: 'ম্যানেজার',
    salesman: 'সেলসম্যান',
    accountant: 'অ্যাকাউন্ট্যান্ট',
    driver: 'ড্রাইভার',
    loader: 'লোডার',
    
    // Permission IDs
    all: 'সব অ্যাক্সেস',
    products: 'প্রোডাক্ট',
    retailers: 'রিটেইলার',
    sales: 'বিক্রয়',
    payments: 'পেমেন্ট',
    stock: 'স্টক',
    reports: 'রিপোর্ট',
    companies: 'কোম্পানি',
    users: 'ইউজার',
    view_deliveries: 'ডেলিভারি',
    Description: 'বিবরণ',
    Permissions: 'পারমিশন',
    Color: 'রঙ',
    AllAccess: 'সব অ্যাক্সেস',
    ManageProducts: 'প্রোডাক্ট ম্যানেজ',
    ManageRetailers: 'রিটেইলার ম্যানেজ',
    CreateSales: 'বিক্রয় তৈরি',
    ManagePayments: 'পেমেন্ট ম্যানেজ',
    ManageStock: 'স্টক ম্যানেজ',
    ViewReports: 'রিপোর্ট দেখুন',
    ManageCompanies: 'কোম্পানি ম্যানেজ',
    ManageUsers: 'ইউজার ম্যানেজ',
    ViewDeliveries: 'ডেলিভারি দেখুন',
    RoleManagement: 'রোল ম্যানেজমেন্ট',
    RoleAdded: 'রোল সফলভাবে যোগ করা হয়েছে',
    RoleUpdated: 'রোল সফলভাবে আপডেট করা হয়েছে',
    RoleDeleted: 'রোল সফলভাবে মুছে ফেলা হয়েছে',
    CannotDeleteSystemRole: 'সিস্টেম রোল মুছা যায়না',
    CannotDeleteRoleWithUsers: 'রোল মুছা যায়না - এই রোলে ইউজার আছে',
    RoleNameRequired: 'রোল নাম আবশ্যক',
    PermissionsRequired: 'অন্তত একটি পারমিশন আবশ্যক',

    // Auth
    Login: 'লগইন',
    ForgotPassword: 'পাসওয়ার্ড ভুলে গেছি?',
    ResetPassword: 'পাসওয়ার্ড রিসেট',
    CurrentPassword: 'বর্তমান পাসওয়ার্ড',
    NewPassword: 'নতুন পাসওয়ার্ড',
    LoginFailed: 'লগইন ব্যর্থ',
    InvalidCredentials: 'ভুল তথ্য',
    PasswordChanged: 'পাসওয়ার্ড সফলভাবে পরিবর্তন',
    PasswordMismatch: 'পাসওয়ার্ড মেলেনি',
    PasswordTooShort: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে',
    SendResetLink: 'রিসেট লিংক পাঠান',
    BackToLogin: 'লগইনে ফিরুন',
    PasswordResetLinkSent: 'পাসওয়ার্ড রিসেট লিংক আপনার ইমেইলে পাঠানো হয়েছে',
    EnterAmount: 'লিখুন',
    TryAgain: 'আবার চেষ্টা করুন',
    Redirecting: 'পুনর্নির্দেশ',
    Access: 'কন্ট্রোল',
    Cheque: 'চেক',
    Or: 'অথবা',
    Default: 'ডিফল্ট',
    AccountDeactivated: 'আপনার অ্যাকাউন্ট নিষ্ক্রিয় করা হয়েছে। অনুগ্রহ করে অ্যাডমিনিস্ট্রেটরের সাথে যোগাযোগ করুন।',
    Page: 'পেজ',

    // Public Chat
    MessageWithDealer: 'ডিলারের সাথে বার্তা',
    NewChat: 'নতুন চ্যাট',
    TrackingCode: 'ট্র্যাকিং কোড',
    YourName: 'আপনার নাম',
    MobileNumber: 'মোবাইল নম্বর',
    StartChat: 'চ্যাট শুরু',
    EnterTrackingCode: 'আপনার ৮-ডিজিটের ট্র্যাকিং কোড লিখুন',
    ContinueChat: 'চ্যাট চালিয়ে যান',
    TypeYourMessage: 'আপনার বার্তা লিখুন...',
    SendFirstMessage: 'আপনার প্রথম বার্তা পাঠান। ডিলার শীঘ্রই উত্তর দেবেন।',
    ChatSubtitle: 'ডিলারকে একটি বার্তা পাঠান অথবা আপনার ট্র্যাকিং কোড লিখুন',
    AskAboutProducts: 'পণ্য নিয়ে জিজ্ঞাসা করুন',
    MessageDealer: 'ডিলারকে মেসেজ দিন',
    QuickAskHint: 'প্রোডাক্টের দাম ও স্টক জানুন',
    QuickMsgHint: 'ডিলারকে একটি বার্তা পাঠান',
    Back: 'পেছনে',
    DealerIsTyping: 'ডিলার লিখছেন...',
    Dealer: 'ডিলার',
    SessionNotFound: 'সেশন পাওয়া যায়নি। অনুগ্রহ করে নতুন চ্যাট শুরু করুন।',
    Checking: 'চেক করা হচ্ছে...',
    Starting: 'শুরু হচ্ছে...',
    Send: 'পাঠান',
    EnterYourName: 'আপনার নাম লিখুন',
    EnterYourPhone: 'আপনার মোবাইল নম্বর লিখুন',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const getInitialLanguage = () => {
    try {
      const saved = localStorage.getItem('dms_language');
      if (saved === 'bn' || saved === 'en') {
        return saved;
      }
    } catch (e) {
      console.error('Error reading language:', e);
    }
    return 'bn';
  };
  
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem('dms_language', language);
  }, [language]);

  useEffect(() => {
    const handleStorage = () => {
      const saved = localStorage.getItem('dms_language');
      if (saved && saved !== language) {
        setLanguage(saved);
      }
    };
    window.addEventListener('storage', handleStorage);
    const interval = setInterval(handleStorage, 500);
    return () => {
      window.removeEventListener('storage', handleStorage);
      clearInterval(interval);
    };
  }, [language]);

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatNumber, toBanglaNumber }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export function formatCurrency(amount, lang = 'en') {
  if (amount === null || amount === undefined || isNaN(amount)) return lang === 'bn' ? '৳ 0' : '৳ 0';
  const formatted = new Intl.NumberFormat('en-BD', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);
  return (lang === 'bn' ? '৳ ' : '৳ ') + (lang === 'bn' ? toBanglaNumber(formatted) : formatted);
}

export function toBanglaNumber(num) {
  const banglaDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
  return String(num).replace(/\d/g, (digit) => banglaDigits[digit]);
}

export function formatNumber(num, lang = 'en') {
  if (num === null || num === undefined || isNaN(num)) return lang === 'bn' ? '০' : '0';
  const formatted = new Intl.NumberFormat('en-BD').format(num);
  return lang === 'bn' ? toBanglaNumber(formatted) : formatted;
}

export function formatDate(dateStr, lang = 'en') {
  if (!dateStr) return '-';
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) return dateStr;
  const formatted = date.toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' });
  return lang === 'bn' ? toBanglaNumber(formatted) : formatted;
}

export function formatDateTime(dateStr, lang = 'en') {
  if (!dateStr) return '-';
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) return dateStr;
  const formatted = date.toLocaleString('en-GB', { 
    day: '2-digit', month: '2-digit', year: 'numeric',
    hour: '2-digit', minute: '2-digit'
  });
  return lang === 'bn' ? toBanglaNumber(formatted) : formatted;
}
